import type { BatchModel } from "../batchTypes";

export function createAppProviderValues(deps: any): {
  wizard: any;
  modeSelect: any;
  workbench: any;
  history: any;
  rulesCenter: any;
  advanced: any;
  system: any;
} {
  const isDockerDev =
    String(deps.config?.runtime?.repo_root || "") === "/app" ||
    String(deps.config?.runtime?.cwd || "") === "/app" ||
    String(deps.config?.runtime?.YGF_APP_ROOT || "") === "/app";
  const workbenchBatches = Array.isArray(deps.batches) ? deps.batches.filter((b: BatchModel) => !b?.archivedAt) : [];
  const historyBatches = Array.isArray(deps.batches) ? deps.batches : [];
  return {
    wizard: {
      wizardStep: deps.wizardStep,
      setWizardStep: deps.setWizardStep,
      mode: deps.mode,
      wizardUploading: deps.wizardUploading,
      handleAddUpload: deps.handleAddUpload,
      wizardTasks: deps.wizardTasks,
      removeTask: deps.removeTask,
      moveTask: deps.moveTask,
      setRoute: deps.setRoute,
      form: deps.form,
      reviewEnabled: deps.reviewEnabled,
      setReviewEnabled: deps.setReviewEnabled,
      batchName: deps.batchName,
      setBatchName: deps.setBatchName,
      outputDir: deps.outputDir,
      chooseOutputDir: deps.chooseOutputDir,
      openPath: deps.openPath,
      subtitleSource: deps.subtitleSource,
      setSubtitleSource: deps.setSubtitleSource,
      regionPickerRect: deps.regionPickerRect,
      setRegionRectSafe: deps.setRegionRectSafe,
      regionPickerSampleFontSize: deps.regionPickerSampleFontSize,
      setFinalSubtitleFontSize: deps.setFinalSubtitleFontSize,
      regionPickerFrameRef: deps.regionPickerFrameRef,
      regionPickerVideoPath: deps.regionPickerVideoPath,
      regionPickerVideoRef: deps.regionPickerVideoRef,
      setRegionPickerVideoReady: deps.setRegionPickerVideoReady,
      setRegionPickerVideoError: deps.setRegionPickerVideoError,
      setRegionPickerVideoInfo: deps.setRegionPickerVideoInfo,
      regionPickerVideoBox: deps.regionPickerVideoBox,
      regionPickerSampleText: deps.regionPickerSampleText,
      regionPickerVideoScale: deps.regionPickerVideoScale,
      saveSubtitleSettings: deps.saveSubtitleSettings,
      hasUnsavedHasSettings: deps.hasUnsavedHasSettings,
      hasUnsavedNoneSettings: deps.hasUnsavedNoneSettings,
      applySavedSubtitleSettings: deps.applySavedSubtitleSettings,
      createBatchAndGo: deps.createBatchAndGo,
      taskCreationBlocked: deps.taskCreationBlocked,
      taskCreationBlockReason: deps.taskCreationBlockReason,
      canRenewInApp: deps.canRenewInApp,
      openRenewalModal: deps.openRenewalModal,
    },
    modeSelect: {
      availableModes: deps.availableModes,
      mode: deps.mode,
      config: deps.config,
      uiPrefs: deps.uiPrefs,
      setMode: deps.setMode,
      setUiPrefs: deps.setUiPrefs,
      saveUiPrefs: deps.saveUiPrefs,
    },
    workbench: {
      batches: workbenchBatches,
      activeBatchId: deps.activeBatchId,
      batchCounts: deps.batchCounts,
      onNewBatch: deps.resetWizard,
      onSetActiveBatchId: deps.setActiveBatchId,
      onOpenTaskDrawer: deps.openTaskDrawer,
      onOpenBatchOutputFolder: deps.openBatchOutputFolder,
      onOpenPath: deps.openPath,
      onOpenDefaultOutputsFolder: deps.openDefaultOutputsFolder,
      onDeliverTaskToOutputDir: deps.deliverTaskToOutputDir,
      onPauseQueue: deps.pauseQueueById,
      onResumeQueue: deps.resumeQueueById,
      onStartQueue: deps.startQueue,
      safeStem: deps.safeStem,
      drawerOpen: deps.drawerOpen,
      drawerTaskIndex: deps.drawerTaskIndex,
      drawerWidth: deps.drawerWidth,
      drawerInitialTab: deps.drawerInitialTab,
      drawerLog: deps.drawerLog,
      drawerLogLoading: deps.drawerLogLoading,
      activeBatch: deps.activeBatch,
      qualityGates: deps.config?.quality_gates,
      isDockerDev,
      onCloseDrawer: deps.onCloseDrawer,
      onResumeTaskInPlace: deps.resumeTaskInPlace,
      onRunReviewAndPoll: deps.runReviewAndPoll,
      onApplyReviewAndRefresh: deps.applyReviewAndRefresh,
      onExportDiagnosticZipForTask: deps.exportDiagnosticZipForTask,
      onOpenCleanupDialog: deps.openCleanupDialog,
      onOpenQualityUpgradeWizardFromTask: deps.openQualityUpgradeWizardFromTask,
      onGoSystem: deps.onGoSystem,
      showTaskLogs: Boolean(deps.uiPrefs?.showTaskLogs),
      onCancelTaskInBatch: deps.cancelTaskInBatch,
      onRestartTaskInBatch: deps.restartTaskInBatch,
      onArchiveBatch: (batchId: string) => {
        deps.setBatches((prev: BatchModel[]) =>
          prev.map((x) => (x.id === batchId ? { ...x, archivedAt: Date.now() } : x)),
        );
        if (deps.activeBatchIdRef?.current === batchId) {
          deps.setActiveBatchId("");
        }
      },
      uiPrefs: deps.uiPrefs,
      onSetUiPrefs: deps.setUiPrefs,
      onSaveUiPrefs: deps.saveUiPrefs,
      taskCreationBlocked: deps.taskCreationBlocked,
      taskCreationBlockReason: deps.taskCreationBlockReason,
      canRenewInApp: deps.canRenewInApp,
      openRenewalModal: deps.openRenewalModal,
    },
    history: {
      batches: historyBatches,
      batchCounts: deps.batchCounts,
      onNewBatch: deps.resetWizard,
      onOpenBatchOutputFolder: deps.openBatchOutputFolder,
      onOpenDeliveredDirForTask: deps.openDeliveredDirForTask,
      taskCreationBlocked: deps.taskCreationBlocked,
      taskCreationBlockReason: deps.taskCreationBlockReason,
      canRenewInApp: deps.canRenewInApp,
      openRenewalModal: deps.openRenewalModal,
      onDeleteBatch: (batchId: string) => {
        deps.setBatches((prev: BatchModel[]) => prev.filter((x) => x.id !== batchId));
        if (deps.activeBatchIdRef?.current === batchId) {
          deps.setActiveBatchId("");
        }
      },
    },
    rulesCenter: {
      rulesError: deps.rulesCenterModel.rulesError,
      rulesLoading: deps.rulesCenterModel.rulesLoading,
      onOpenRules: deps.rulesCenterModel.onOpenRules,
      onSaveGlobalRules: deps.rulesCenterModel.onSaveGlobalRules,
      onUploadRulesetFile: deps.rulesCenterModel.onUploadRulesetFile,
      onDownloadGlobalRules: deps.rulesCenterModel.onDownloadGlobalRules,
      globalReplaceRows: deps.rulesCenterModel.globalReplaceRows,
      onAddGlobalReplaceRow: deps.rulesCenterModel.onAddGlobalReplaceRow,
      onRemoveGlobalReplaceRow: deps.rulesCenterModel.onRemoveGlobalReplaceRow,
      onUpdateGlobalReplaceRow: deps.rulesCenterModel.onUpdateGlobalReplaceRow,
      batchReplaceRows: deps.rulesCenterModel.batchReplaceRows,
      onAddBatchReplaceRow: deps.rulesCenterModel.onAddBatchReplaceRow,
      onRemoveBatchReplaceRow: deps.rulesCenterModel.onRemoveBatchReplaceRow,
      onUpdateBatchReplaceRow: deps.rulesCenterModel.onUpdateBatchReplaceRow,
      onDownloadBatchOverride: deps.rulesCenterModel.onDownloadBatchOverride,
      onImportBatchOverride: deps.rulesCenterModel.onImportBatchOverride,
      onClearBatchOverride: deps.rulesCenterModel.onClearBatchOverride,
      currentBatchRulesetOverride: deps.rulesCenterModel.currentBatchRulesetOverride,
      applyBatchOverrideFromDoc: deps.rulesCenterModel.applyBatchOverrideFromDoc,
      templates: deps.rulesCenterModel.templates,
      templatesLoading: deps.rulesCenterModel.templatesLoading,
      templatesError: deps.rulesCenterModel.templatesError,
      refreshRulesTemplates: deps.rulesCenterModel.refreshRulesTemplates,
      fetchTemplate: deps.rulesCenterModel.fetchTemplate,
      saveTemplate: deps.rulesCenterModel.saveTemplate,
      removeTemplate: deps.rulesCenterModel.removeTemplate,
      createTemplate: deps.rulesCenterModel.createTemplate,
      importTemplateFile: deps.rulesCenterModel.importTemplateFile,
    },
    advanced: {
      config: deps.config,
      mode: deps.mode,
      advancedShowAll: deps.advancedShowAll,
      setAdvancedShowAll: deps.setAdvancedShowAll,
      form: deps.form,
      toggleMeta: deps.toggleMeta,
      paramMeta: deps.paramMeta,
      textMeta: deps.textMeta,
      stageOfToggle: deps.stageOfToggle,
      riskTagColor: deps.riskTagColor,
      uiPrefs: deps.uiPrefs,
      setUiPrefs: deps.setUiPrefs,
      saveUiPrefs: deps.saveUiPrefs,
      devToolsEnabled: deps.devToolsEnabled,
    },
    system: {
      apiBase: deps.apiBase,
      health: deps.health,
      hardware: deps.hardware,
      loadingBoot: deps.loadingBoot,
      onBootstrap: deps.bootstrap,
      mode: deps.mode,
      requireLocalPacks: deps.requireLocalPacks,
      modelsReady: deps.modelsReady,
      modelsRoot: deps.modelsRoot,
      modelsZipHint: deps.modelsZipHint,
      missingLabels: deps.missingLabels,
      modelsError: deps.modelsError,
      modelsImporting: deps.modelsImporting,
      onPickModels: deps.handlePickModels,
      ollamaReady: deps.ollamaReady,
      ollamaPortOpen: deps.ollamaPortOpen,
      ollamaRoot: deps.ollamaRoot,
      ollamaModelsRoot: deps.ollamaModelsRoot,
      ollamaZipHint: deps.ollamaZipHint,
      ollamaProcessorSummary: deps.ollamaProcessorSummary,
      ollamaAcceleration: deps.ollamaAcceleration,
      ollamaActiveModels: deps.ollamaActiveModels,
      ollamaUsesGpu: deps.ollamaUsesGpu,
      ollamaError: deps.ollamaError,
      ollamaImporting: deps.ollamaImporting,
      ollamaStarting: deps.ollamaStarting,
      ollamaLoading: deps.ollamaLoading,
      onPickOllama: deps.handlePickOllama,
      onEnsureOllama: deps.handleEnsureOllama,
      onRefreshOllamaStatus: deps.refreshOllamaStatus,
      runtimeStatus: deps.runtimeStatus,
      runtimeLoading: deps.runtimeLoading,
      runtimeError: deps.runtimeError,
      backendRestarting: deps.backendRestarting,
      onRefreshRuntimeStatus: deps.refreshRuntimeStatus,
      onRestartBackend: deps.handleRestartBackend,
      uiPrefs: deps.uiPrefs,
      preset: deps.preset,
      allowedPresetOptions: deps.allowedPresetOptions,
      devToolsEnabled: deps.devToolsEnabled,
      onSetUiPrefs: deps.setUiPrefs,
      onSaveUiPrefs: deps.saveUiPrefs,
      onLoadUiPrefs: deps.loadUiPrefs,
      onSetMode: deps.setMode,
      onSetPreset: deps.setPreset,
      form: deps.form,
      authUserEmail: deps.authUserEmail,
      authStatusText: deps.authStatusText,
      authLicenseExpireAt: deps.authLicenseExpireAt,
      authLicenseLoading: deps.authLicenseLoading,
      onAuthLogout: deps.handleAuthLogout,
      canRenewInApp: deps.canRenewInApp,
      openRenewalModal: deps.openRenewalModal,
    },
  };
}

