#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import statistics
import sys
import time
import wave
from pathlib import Path
from typing import Any, Dict, List

repo_root = Path(__file__).resolve().parents[2]
if str(repo_root) not in sys.path:
    sys.path.insert(0, str(repo_root))

from pipelines.lib.asr.lite_asr import Segment
from pipelines.lib.text.srt_io import read_srt_texts_ordered
from pipelines.lib.tts.lite_tts import (
    build_coqui_tts,
    build_kokoro_tts,
    save_audio,
    synthesize_segments,
    synthesize_segments_coqui,
    synthesize_segments_kokoro,
)


DEFAULT_CANDIDATES: List[Dict[str, str]] = [
    {"id": "piper", "label": "Piper"},
    {"id": "kokoro_onnx", "label": "Kokoro ONNX"},
    {"id": "coqui_xtts", "label": "Coqui XTTS v2"},
]


def _read_jsonl(path: Path) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    for line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = line.strip()
        if not line:
            continue
        obj = json.loads(line)
        if isinstance(obj, dict):
            rows.append(obj)
    return rows


def _write_json(path: Path, data: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def _candidate_entry(results: Dict[str, Any], candidate_id: str) -> Dict[str, Any]:
    for item in results["candidates"]:
        if item["id"] == candidate_id:
            return item
    raise KeyError(candidate_id)


def _load_segments(audio_json: Path, eng_srt: Path) -> List[Segment]:
    data = json.loads(audio_json.read_text(encoding="utf-8", errors="ignore") or "[]")
    base_segments = [Segment(**item) for item in data if isinstance(item, dict)]
    eng_texts = read_srt_texts_ordered(eng_srt)
    out: List[Segment] = []
    for idx, seg in enumerate(base_segments):
        tr = eng_texts[idx].strip() if idx < len(eng_texts) else ""
        out.append(Segment(start=seg.start, end=seg.end, text=seg.text, translation=tr))
    return out


def _wav_duration_s(path: Path) -> float:
    with wave.open(str(path), "rb") as wav_in:
        frames = float(wav_in.getnframes())
        rate = float(wav_in.getframerate() or 1.0)
        return max(0.0, frames / rate)


def build_manifest(cases_path: Path, cases_count: int, run_id: str, hardware_tier: str, notes: str, eng_root: Path) -> Dict[str, Any]:
    return {
        "phase": "lite_phase1",
        "capability": "tts",
        "run_id": run_id,
        "hardware_tier": hardware_tier,
        "cases_path": str(cases_path),
        "cases_count": cases_count,
        "eng_root": str(eng_root),
        "notes": notes,
        "baseline_candidate": "piper",
        "candidates": DEFAULT_CANDIDATES,
        "decision_rules": {
            "hard_metrics": ["elapsed_s_mean", "fail_rate", "artifacts_ok_rate", "overflow_rate"],
            "allow_replace_only_if": [
                "tts_stable_on_normal_tier",
                "artifacts_ok_rate_not_worse_than_baseline",
                "subjective_score_clearly_better",
            ],
        },
        "tuned_profiles": {
            "piper": {"split_len": 80, "max_speed": 1.08, "align_mode": "atempo", "voice": "en_US-amy-low"},
            "kokoro_onnx": {"voice": "af_sarah", "language": "en-us", "speed": 1.0, "split_len": 100, "max_speed": 1.08, "align_mode": "atempo"},
            "coqui_xtts": {"device": "cpu", "language": "en", "split_len": 100, "max_speed": 1.08, "align_mode": "atempo"},
        },
    }


def build_results_template(run_id: str, hardware_tier: str) -> Dict[str, Any]:
    return {
        "phase": "lite_phase1",
        "capability": "tts",
        "run_id": run_id,
        "hardware_tier": hardware_tier,
        "baseline_candidate": "piper",
        "candidates": [
            {
                "id": item["id"],
                "label": item["label"],
                "metrics": {
                    "elapsed_s_mean": None,
                    "passed_rate": None,
                    "fail_rate": None,
                    "artifacts_ok_rate": None,
                    "added_cost_vs_baseline": None,
                    "subjective_score": None,
                    "replace_recommendation": None,
                    "overflow_rate": None,
                    "duration_diff_s_mean": None,
                },
                "case_results": [],
                "notes": "",
            }
            for item in DEFAULT_CANDIDATES
        ],
    }


def build_readme(run_id: str, hardware_tier: str, cases_count: int) -> str:
    return f"""# lite_phase1 TTS bakeoff

run_id: `{run_id}`
hardware_tier: `{hardware_tier}`
cases_count: `{cases_count}`

This folder is generated by `lite_phase1_tts_bakeoff.py`.

Files:
- `manifest.json`: static experiment definition
- `results_template.json`: measured result summary
- `runs/<candidate>/<case>/tts_full.wav`: per-case candidate output

Phase1 TTS candidates:
- `piper`
- `kokoro_onnx`
- `coqui_xtts`
"""


def main() -> None:
    ap = argparse.ArgumentParser(description="Run phase1 TTS bakeoff with tuned Piper / Kokoro ONNX / Coqui XTTS profiles.")
    ap.add_argument("--cases", type=Path, required=True, help="Input cases jsonl")
    ap.add_argument("--eng-root", type=Path, required=True, help="Directory containing per-case eng.srt under <case_id>/eng.srt")
    ap.add_argument("--out-dir", type=Path, required=True, help="Output directory")
    ap.add_argument("--hardware-tier", type=str, default="normal", choices=["normal", "mid", "high"])
    ap.add_argument("--run-id", type=str, required=True, help="Run identifier")
    ap.add_argument("--notes", type=str, default="", help="Optional note")
    ap.add_argument("--sample-rate", type=int, default=24000)
    ap.add_argument("--limit", type=int, default=0)
    ap.add_argument("--candidate-ids", type=str, default="")
    ap.add_argument("--piper-model", type=Path, default=Path("assets/models/lite_tts_piper/en_US-amy-low.onnx"))
    ap.add_argument("--piper-bin", type=str, default="piper")
    ap.add_argument("--kokoro-model", type=Path, default=Path("assets/models/lite_tts_kokoro_onnx/kokoro-v1.0.onnx"))
    ap.add_argument("--kokoro-voices", type=Path, default=Path("assets/models/lite_tts_kokoro_onnx/voices-v1.0.bin"))
    ap.add_argument("--kokoro-voice", type=str, default="af_sarah")
    ap.add_argument("--coqui-model", type=str, default="tts_models/multilingual/multi-dataset/xtts_v2")
    ap.add_argument("--coqui-device", type=str, default="cpu")
    args = ap.parse_args()

    rows = _read_jsonl(args.cases)
    if args.limit and args.limit > 0:
        rows = rows[: args.limit]
    want = {part.strip() for part in str(args.candidate_ids or "").split(",") if part.strip()}
    selected = [item for item in DEFAULT_CANDIDATES if not want or item["id"] in want]

    out_dir = args.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)
    manifest = build_manifest(args.cases, len(rows), args.run_id, args.hardware_tier, args.notes, args.eng_root)
    manifest["candidates"] = selected
    results = build_results_template(args.run_id, args.hardware_tier)
    results["candidates"] = [item for item in results["candidates"] if not want or item["id"] in want]

    candidate_runtimes: Dict[str, Any] = {}
    baseline_elapsed = None
    for cand in selected:
        cid = cand["id"]
        if cid == "piper":
            candidate_runtimes[cid] = None
        elif cid == "kokoro_onnx":
            candidate_runtimes[cid] = build_kokoro_tts(args.kokoro_model, args.kokoro_voices)
        elif cid == "coqui_xtts":
            candidate_runtimes[cid] = build_coqui_tts(args.coqui_model, device=args.coqui_device)
        else:
            raise RuntimeError(f"unknown TTS candidate: {cid}")

        entry = _candidate_entry(results, cid)
        case_results: List[Dict[str, Any]] = []
        elapsed_ok: List[float] = []
        duration_diffs: List[float] = []
        overflow_hits = 0
        fail_count = 0
        ok_count = 0

        for row in rows:
            case_id = str(row.get("id") or "").strip()
            if not case_id:
                continue
            audio_json = Path(str(row["audio_json"]))
            eng_srt = args.eng_root / case_id / "eng.srt"
            segments = _load_segments(audio_json, eng_srt)
            target_duration_s = max((float(seg.end) for seg in segments), default=0.0)
            case_dir = out_dir / "runs" / cid / case_id
            work_dir = case_dir / "segments"
            case_dir.mkdir(parents=True, exist_ok=True)
            tts_wav = case_dir / "tts_full.wav"
            t0 = time.time()
            err = ""
            status = "ok"
            artifact_ok = False
            duration_s = None
            try:
                if cid == "piper":
                    combined_audio = synthesize_segments(
                        segments=segments,
                        model_path=args.piper_model,
                        work_dir=work_dir,
                        piper_bin=args.piper_bin,
                        split_len=80,
                        max_speed=1.08,
                        align_mode="atempo",
                    )
                elif cid == "kokoro_onnx":
                    combined_audio = synthesize_segments_kokoro(
                        segments=segments,
                        kokoro=candidate_runtimes[cid],
                        work_dir=work_dir,
                        sample_rate=args.sample_rate,
                        voice=args.kokoro_voice,
                        language="en-us",
                        speed=1.0,
                        split_len=100,
                        max_speed=1.08,
                        align_mode="atempo",
                    )
                else:
                    combined_audio = synthesize_segments_coqui(
                        segments=segments,
                        tts=candidate_runtimes[cid],
                        work_dir=work_dir,
                        sample_rate=args.sample_rate,
                        language="en",
                        split_len=100,
                        max_speed=1.08,
                        align_mode="atempo",
                    )
                save_audio(combined_audio, tts_wav, sample_rate=args.sample_rate)
                duration_s = _wav_duration_s(tts_wav)
                artifact_ok = tts_wav.exists() and tts_wav.stat().st_size > 0
                if not artifact_ok:
                    status = "artifact_missing"
            except Exception as exc:
                status = "failed"
                err = str(exc)
            elapsed_s = round(time.time() - t0, 4)
            duration_diff_s = None
            if artifact_ok and duration_s is not None:
                ok_count += 1
                elapsed_ok.append(elapsed_s)
                duration_diff_s = round(duration_s - target_duration_s, 4)
                duration_diffs.append(duration_diff_s)
                if abs(duration_diff_s) > 0.35:
                    overflow_hits += 1
            else:
                fail_count += 1
            case_results.append(
                {
                    "id": case_id,
                    "status": status,
                    "elapsed_s": elapsed_s,
                    "artifact_ok": artifact_ok,
                    "tts_wav": str(tts_wav) if artifact_ok else "",
                    "target_duration_s": round(target_duration_s, 4),
                    "duration_s": duration_s,
                    "duration_diff_s": duration_diff_s,
                    "eng_preview": [str(seg.translation or "").strip() for seg in segments[:4]],
                    "error": err,
                }
            )

        total = max(1, len(case_results))
        entry["case_results"] = case_results
        entry["metrics"] = {
            "elapsed_s_mean": round(statistics.mean(elapsed_ok), 4) if elapsed_ok else None,
            "passed_rate": round(ok_count / total, 4),
            "fail_rate": round(fail_count / total, 4),
            "artifacts_ok_rate": round(ok_count / total, 4),
            "added_cost_vs_baseline": None,
            "subjective_score": None,
            "replace_recommendation": None,
            "overflow_rate": round(overflow_hits / total, 4),
            "duration_diff_s_mean": round(statistics.mean(duration_diffs), 4) if duration_diffs else None,
        }
        entry["notes"] = "await user listening review before final decision"
        if cid == "piper":
            baseline_elapsed = entry["metrics"]["elapsed_s_mean"]

    for entry in results["candidates"]:
        val = entry["metrics"].get("elapsed_s_mean")
        if val is not None and baseline_elapsed is not None:
            entry["metrics"]["added_cost_vs_baseline"] = round(float(val) - float(baseline_elapsed), 4)

    _write_json(out_dir / "manifest.json", manifest)
    _write_json(out_dir / "results_template.json", results)
    (out_dir / "README.md").write_text(build_readme(args.run_id, args.hardware_tier, len(rows)), encoding="utf-8")
    print(str(out_dir / "manifest.json"))
    print(str(out_dir / "results_template.json"))


if __name__ == "__main__":
    main()
